language: python
python:
  - "3.6"

before_script:
  - pip install pylint

script:
  - pylint torchrl experiments
  - pip install .

deploy:
  provider: pypi
  user: $PYPI_USERNAME
  password: $PYPI_PASSWORD
  on:
    tags: true
