language: python
python:
  - "3.6"

before_script:
  - pip install -r requirements_dev.txt

script:
  - pylint torchrl examples
  - pip install .

deploy:
  provider: pypi
  user: $PYPI_USERNAME
  password: $PYPI_PASSWORD
  on:
    tags: true
